version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: es-finops
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.monitoring.collection.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -k -s http://localhost:9200 >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 50

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kb-finops
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=please_change_me_32chars_minimum_______
      - XPACK_REPORTING_ENABLED=true
      - SERVER_PUBLICBASEURL=http://localhost:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"

volumes:
  esdata:
    driver: local
